#webpath  /home/huxq/NETDISK/web/
########################shell variable################################
upload:
  realpath: /home/iamges/home/iamges/articleTypeImages/
liunx:
  ipAddress: 10.24.34.185
  username: huxq
  password: 123456
  port: 22
########################env config##################################
server:
  port: 7903
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
spring:
 #上传文件大小
  http:
    multipart:
      maxFileSize: 50Mb
      maxRequestSize: 500MB
  application:
    name: fylat_service
  datasource:

#    url: jdbc:postgresql://localhost:5432/postgres?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
#    username: handongchen
#    password: 123456

#    url: jdbc:postgresql://10.24.34.185:5432/postgres?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
#    username: huxq

#    url: jdbc:postgresql://192.168.4.41:5432/postgres?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
#    username: postgres
#    password: postgres
#
#    driver-class-name: org.postgresql.Driver
    url: jdbc:mysql://106.2.11.94:3306/zz_wechat?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123&456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 600000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
      minimum-idle: 5

logging:
  level:
    root: INFO
    org.springframework.jdbc.core: DEBUG
    com.kingweather: DEBUG